name: Scraping Chrome OS boards
on:
  schedule:
    - cron: "0 0 * * *" # run at the start of every day
  workflow_dispatch:

jobs:
  update-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3

      - name: Installing pip + dependencies
        run: sudo apt-get install python3-pip && pip3 install requests beautifulsoup4

      - name: Running scraper script
        run: python3 ./.github/scripts/scrape-boards.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Disable setting repo owner as commit author
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Updating devices-autogen.json

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: 'device-support/devices-autogen.json device-support/devices-list.json'